# Generated by Django 5.2.6 on 2025-09-16 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255, verbose_name='Пользователь')),
                ('name', models.CharField(max_length=255, verbose_name='Название продукта')),
                ('image', models.ImageField(upload_to='products', verbose_name='Фото продукта')),
                ('amount', models.IntegerField(verbose_name='Сумма')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
