# Generated by Django 5.2.6 on 2025-09-21 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='categories',
        ),
    ]
